"""Subject-level statistical comparison of Method1 vs Method2 vs Method3.

Reads per-image CSVs generated by generate_method_perimage.py, aggregates
to subject level, and performs pairwise permutation tests with bootstrap
confidence intervals and Holm correction.

Usage:
    python tools/method_comparison_stats.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Tuple

import numpy as np
import pandas as pd
from scipy.stats import friedmanchisquare


# ---------------------------------------------------------------------------
# Helpers (from tools/segformer_stats.py)
# ---------------------------------------------------------------------------

def _latest(results_dir: Path, pattern: str) -> Optional[Path]:
    files = sorted(results_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0] if files else None


def _subject_id_from_filename(filename: str) -> str:
    return str(filename).split("-", 1)[0]


def _paired_perm_p(diff: np.ndarray, n_perm: int = 20000, seed: int = 0) -> Tuple[float, float]:
    """Paired permutation test (sign-flip). Returns (observed_mean_diff, p_value)."""
    rng = np.random.default_rng(seed)
    obs = float(diff.mean())
    signs = rng.choice(np.array([-1.0, 1.0]), size=(n_perm, diff.size), replace=True)
    perm = (signs * diff[None, :]).mean(axis=1)
    p = float((np.abs(perm) >= abs(obs)).mean())
    return obs, p


def _paired_boot_ci(diff: np.ndarray, n_boot: int = 20000, seed: int = 1) -> Tuple[float, float]:
    """Bootstrap 95% CI on subject-level mean difference."""
    rng = np.random.default_rng(seed)
    n = diff.size
    idx = rng.integers(0, n, size=(n_boot, n))
    boot = diff[idx].mean(axis=1)
    lo, hi = np.quantile(boot, [0.025, 0.975])
    return float(lo), float(hi)


def holm_adjust(pvals: dict) -> dict:
    """Holm-Bonferroni correction for family-wise error rate control."""
    items = sorted(pvals.items(), key=lambda kv: kv[1])
    m = len(items)
    out = {}
    prev = 0.0
    for j, (name, p) in enumerate(items, start=1):
        adj = p * (m - j + 1)
        adj = min(1.0, adj)
        adj = max(prev, adj)
        prev = adj
        out[name] = adj
    return out


def fmt_p(p: float) -> str:
    """Format p-value: show <5e-5 when 0."""
    if p == 0.0:
        return "<5e-5"
    if p < 0.001:
        return f"{p:.2e}"
    return f"{p:.4f}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results_dir", type=str, default="results")
    ap.add_argument("--n_perm", type=int, default=20000)
    ap.add_argument("--n_boot", type=int, default=20000)
    args = ap.parse_args()

    results_dir = Path(args.results_dir)
    if not results_dir.is_absolute():
        results_dir = Path(__file__).resolve().parent.parent / results_dir

    # Load per-image CSVs
    method_csvs = {}
    for mid in [1, 2, 3]:
        p = _latest(results_dir, f"cv_method{mid}_perimage_*.csv")
        if p is None and mid == 3:
            # Fallback: use full_vs_exposed CSV (filter to ransac_whole)
            p = _latest(results_dir, "cv_method3_full_vs_exposed_perimage_*.csv")
        if p is None:
            print(f"WARNING: No per-image CSV found for Method{mid}")
            continue
        method_csvs[mid] = p
        print(f"Method{mid}: {p.name}")

    if len(method_csvs) < 2:
        print("ERROR: Need at least 2 methods to compare.")
        return 1

    # Subject-level aggregation
    subj = {}
    for mid, csv_path in method_csvs.items():
        df = pd.read_csv(csv_path)
        # Method3 full_vs_exposed CSV has a 'mode' column; filter to ransac_whole
        if "mode" in df.columns:
            df = df[df["mode"] == "ransac_whole"].copy()
            print(f"  -> Filtered Method{mid} to mode='ransac_whole': {len(df)} rows")
        if "subject_id" not in df.columns:
            df["subject_id"] = df["filename"].astype(str).map(_subject_id_from_filename)
        subj_mean = df.groupby("subject_id")[["mean", "eyelid", "iris", "pupil"]].mean()
        subj[mid] = subj_mean

    # Subject-level ranking
    print("\n" + "=" * 70)
    print("SUBJECT-LEVEL RANKING (Mean Dice)")
    print("=" * 70)
    rankings = []
    for mid, sm in subj.items():
        rankings.append((mid, float(sm["mean"].mean()), int(sm.shape[0])))
    rankings.sort(key=lambda x: x[1], reverse=True)

    print(f"\n| Method | Subject mean Dice | n_subjects |")
    print(f"|---|---:|---:|")
    for mid, mean_dice, n_sub in rankings:
        label = {1: "Method1 (ellipse regression)", 2: "Method2 (edge -> fitting)", 3: "Method3 (6-class segmentation)"}[mid]
        bold = "**" if mid == rankings[0][0] else ""
        print(f"| {label} | {bold}{mean_dice:.6f}{bold} | {n_sub} |")

    # Per-class subject-level ranking
    print(f"\n| Method | Eyelid | Iris | Pupil | Mean |")
    print(f"|---|---:|---:|---:|---:|")
    for mid, _, n_sub in rankings:
        sm = subj[mid]
        label = {1: "Method1", 2: "Method2", 3: "Method3"}[mid]
        print(f"| {label} | {sm['eyelid'].mean():.6f} | {sm['iris'].mean():.6f} | {sm['pupil'].mean():.6f} | {sm['mean'].mean():.6f} |")

    # Omnibus test: Friedman (non-parametric repeated measures)
    if len(subj) >= 3:
        common_all = subj[1].index.intersection(subj[2].index).intersection(subj[3].index)
        fr_stat, fr_p = friedmanchisquare(
            subj[1].loc[common_all, "mean"].to_numpy(),
            subj[2].loc[common_all, "mean"].to_numpy(),
            subj[3].loc[common_all, "mean"].to_numpy(),
        )
        print("\n" + "=" * 70)
        print("OMNIBUS TEST: Friedman (non-parametric repeated measures)")
        print("=" * 70)
        print(f"  n_subjects = {len(common_all)}")
        print(f"  Friedman chi-squared = {fr_stat:.4f}")
        print(f"  p-value = {fmt_p(fr_p)}")
        if fr_p < 0.05:
            print("  -> Significant (p < 0.05): at least one method differs. Proceeding to post-hoc pairwise tests.")
        else:
            print("  -> Not significant: no evidence of difference among methods.")

    # Pairwise comparisons (post-hoc)
    pairs = []
    if 3 in subj and 1 in subj:
        pairs.append((3, 1, "Method3 (6-class segmentation)", "Method1 (ellipse regression)"))
    if 3 in subj and 2 in subj:
        pairs.append((3, 2, "Method3 (6-class segmentation)", "Method2 (edge -> fitting)"))
    if 2 in subj and 1 in subj:
        pairs.append((2, 1, "Method2 (edge -> fitting)", "Method1 (ellipse regression)"))

    if not pairs:
        print("\nNo pairwise comparisons possible.")
        return 0

    print("\n" + "=" * 70)
    print("PAIRWISE COMPARISONS (subject-level paired)")
    print("=" * 70)

    comp_results = []
    pvals_raw = {}
    seed_offset = 20

    for a_id, b_id, a_label, b_label in pairs:
        common = subj[a_id].index.intersection(subj[b_id].index)
        diff = (subj[a_id].loc[common, "mean"].to_numpy() - subj[b_id].loc[common, "mean"].to_numpy()).astype(float)

        obs, p = _paired_perm_p(diff, n_perm=args.n_perm, seed=seed_offset)
        lo, hi = _paired_boot_ci(diff, n_boot=args.n_boot, seed=seed_offset + 1)
        win = float((diff > 0).mean())
        seed_offset += 2

        key = f"Method{a_id}-Method{b_id}"
        pvals_raw[key] = p
        comp_results.append(dict(
            a_id=a_id, b_id=b_id,
            a_label=a_label, b_label=b_label,
            n_subjects=int(len(common)),
            mean_diff=float(obs), ci_lo=float(lo), ci_hi=float(hi),
            win_rate=win, p_perm=p, key=key,
        ))

    # Holm correction
    p_holm = holm_adjust(pvals_raw)

    # Print comparison table
    print(f"\n| Comparison (A - B) | n_subjects | mean_diff | 95% CI | win_rate | p_perm | p_holm |")
    print(f"|---|---:|---:|---|---:|---:|---:|")
    for c in comp_results:
        holm_val = p_holm[c["key"]]
        print(
            f"| Method{c['a_id']} - Method{c['b_id']} "
            f"| {c['n_subjects']} "
            f"| {c['mean_diff']:+.6f} "
            f"| [{c['ci_lo']:+.6f}, {c['ci_hi']:+.6f}] "
            f"| {c['win_rate']:.3f} "
            f"| {fmt_p(c['p_perm'])} "
            f"| {fmt_p(holm_val)} |"
        )

    # Per-class pairwise comparisons
    for metric in ["eyelid", "iris", "pupil"]:
        print(f"\n--- {metric.upper()} ---")
        print(f"| Comparison | mean_diff | 95% CI | p_perm |")
        print(f"|---|---:|---|---:|")
        for a_id, b_id, a_label, b_label in pairs:
            common = subj[a_id].index.intersection(subj[b_id].index)
            diff = (subj[a_id].loc[common, metric].to_numpy() - subj[b_id].loc[common, metric].to_numpy()).astype(float)
            obs, p = _paired_perm_p(diff, n_perm=args.n_perm, seed=seed_offset)
            lo, hi = _paired_boot_ci(diff, n_boot=args.n_boot, seed=seed_offset + 1)
            seed_offset += 2
            print(f"| Method{a_id} - Method{b_id} | {obs:+.6f} | [{lo:+.6f}, {hi:+.6f}] | {fmt_p(p)} |")

    # Save results CSV
    out_csv = results_dir / "method_comparison_stats.csv"
    rows = []
    for c in comp_results:
        rows.append(dict(
            comparison=f"Method{c['a_id']}-Method{c['b_id']}",
            n_subjects=c["n_subjects"],
            mean_diff=c["mean_diff"],
            ci95_low=c["ci_lo"],
            ci95_high=c["ci_hi"],
            win_rate=c["win_rate"],
            p_perm=c["p_perm"],
            p_holm=p_holm[c["key"]],
        ))
    pd.DataFrame(rows).to_csv(out_csv, index=False)
    print(f"\nSaved: {out_csv}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
